### ISSUE TITLE
Bower.json not present

### ISSUE THREAD

**Issue by spidie** [dpnova/goldcoast-blockchain-meetup#1]
In README.md when I run the 
```
bower install 
```
command as instructed I just get
```
dalts@wallaroo ~/work/GCBC/MultiSigWallet/dapp $ bower install
bower ENOENT No bower.json present
```
Can see a bower.json in the repo or any of the other branches, so not sure how this ever worked for you. The core doco also says the same so I am probably missing something. I'm on linux, node 6.11.3.

**Comment by ghost** [comment]
We had one other person at the event with this issue and the solution for them was to just do 
``` 
npm run start 
```
instead and it let them them access the web interface

**Comment by dpnova** [comment]
Thanks @troowala - HTH @spidie
