### ISSUE TITLE
Compile screen looks different

### ISSUE THREAD

**Issue by spidie** [dpnova/goldcoast-blockchain-meetup#2]
My compile screen looks a bit different to yours.

![screenshot from 2018-06-22 05-52-19](https://user-images.githubusercontent.com/20995/41745743-573e0286-75eb-11e8-8676-a1391772c920.png)

Also on the next screen I don't get create button, just deploy, but that might be from previous problem.

**Comment by dpnova** [comment]
I don't use remix much - thoughts here @troowala ?

**Comment by ghost** [comment]
screenshots in the doc are from a slightly older version of remix. it's normal for it to say Deploy now instead of Create.
